Update Comment style + Implement scheduling [Untested]

diff --git a/timemachine b/timemachine
--- a/timemachine
+++ b/timemachine
@@ -2,6 +2,7 @@
 #
 # https://serverfault.com/questions/834994/rsync-only-keep-10-backup-folders
 
+
 ################################################################################
 # Variables
 ################################################################################
@@ -18,6 +19,10 @@ MY_DATE="2018-12-22"
 # cmd [-r] <src> <dst> [rsync opts]
 verbose=   # -v Verbose output
 
+# Console text preferences
+underline="$(tput smul)"
+bold="$(tput bold)"
+normal="$(tput sgr0)"
 
 
 ################################################################################
@@ -83,10 +88,10 @@ logerr() {
 }
 
 
-
 ################################################################################
 # Parsing + Validation Functions
 ################################################################################
+
 parse_args() {
 	# Parse input args with getopts
 	while getopts :vhV-: opt; do
@@ -110,7 +115,7 @@ parse_args() {
 			v | verbose)
 				verbose="verbose"
 				;;
-			\?)	logerr "Unknown option -$OPTARG, see -h for help."
+			\?)	logerr "Unknown option: -$OPTARG, see -h for help."
 				exit 2
 				;;
 			*)	logerr "Unknown option --$opt, see -h for help."
@@ -124,6 +129,7 @@ parse_args() {
 ################################################################################
 # Entrypoint: Validate cmd args
 ################################################################################
+
 validate_args() {
 	# Check arg count
 	[ "${#}" -lt "2" ] && logerr "<source> and <destination> are required. See -h for help." && exit 1
@@ -134,7 +140,7 @@ validate_args() {
 	# Target directory check
 	if [ ! -d "${2}" ] && [ ! -f "${2}" ]; then
 		echo "Target directory does not exist."
-		echo "Would you like to create a new one?[y/n]: "
+		printf "Would you like to create a new one?${bold}[y/n]${normal}: "
 		read -r response
 		if [ "$response" != "${response#[Yy]}" ] ;then
 			mkdir "${2}"
@@ -154,13 +160,11 @@ validate_args() {
 # Main Backup Routine Functions
 ################################################################################
 
-###
-### 1/3 Incremental, resumable and atomic rsync backup
-###
-
 # [incremental] --link-dest:          Used to hardlink files which are equal (instead of re-copying them)
 # [resume]      --partial-dir:        Where to store unfinished files for resume
 # [atomic]      ${BACKUP_INPROGRESS}: Tmp dest dir for atomic operations
+
+# 1/3 Incremental, resumable and atomic rsync backup
 begin_backup() {
 	logmsg "Starting incremental backup"
 	logmsg "\$ rsync $* ${SRC} ${DEST}/${BACKUP_INPROGRESS}"
@@ -186,21 +190,14 @@ begin_backup() {
 	fi
 }
 
-
-###
-### 2/3 Finish atomic operation
-###
+# 2/3 Finish atomic operation
 complete_atomic_op() {
 	# Move temporary atomic directory to chosen dest directory
 	logmsg "\$ mv ${BACKUP_INPROGRESS} ${BACKUP}"
 	mv "${DEST}/${BACKUP_INPROGRESS}" "${DEST}/${BACKUP}"
 }
 
-
-
-###
-### 3/3 Latest symlink
-###
+# 3/3 Latest symlink
 point_new_head() {
 	# Remove current 'latest' symlink
 	if [ -L "${DEST}/${BACKUP_LATEST}" ]; then
@@ -212,6 +209,54 @@ point_new_head() {
 	logmsg "\$ ln -s ${BACKUP} ${BACKUP_LATEST}"
 	ln -s "${BACKUP}" "${DEST}/${BACKUP_LATEST}"
 }
+
+
+################################################################################
+# Scheduling Backups
+################################################################################
+
+# Ask user if they would like to schedule this backup in a timely manner
+prompt_user() {
+	printf "\nWould you like to schedule this backup periodically?${bold}[y/n]:${normal} "
+	read -r response
+	if [ "$response" != "${response#[Yy]}" ] ;then
+		present_menu
+	else
+		logmsg "Backup not scheduled periodically. Quitting..." && exit 1
+	fi
+}
+
+present_menu() {
+	echo "\n${bold}Scheduling Options:${normal}\n"
+	echo "1. Hourly	2. Weekly	3.Quit\n"
+	printf "Please choose an option from the menu above to schedule your backup ${bold}[1-3]${normal}: "
+	read -r response
+	case $response in
+		1)
+			# Every Hour
+			schedule_job "0 * * * *"
+			;;
+		2)
+			# Every Sunday Midnight
+			schedule_job "0 0 * * 0"
+			;;
+		3)
+			echo "Quitting..." && exit
+			;;
+		*)
+			echo "${bold}Invalid Selection${normal}. Quitting..." && exit
+			;;
+		esac
+}
+
+schedule_job() {
+	# EXAMPLE CRONTAB COMMAND
+	# crontab -l | { cat; echo "00 09 * * 1-5 echo hello"; } | crontab -
+	echo "${@}"
+	crontab -l | { cat; echo "${@} timemachine ${SRC} ${DEST}"; } | crontab -
+	# Check if task set successfully
+}
+
 
 ################################################################################
 # Main Entrypoint
@@ -246,7 +291,8 @@ begin_backup "$@"
 complete_atomic_op
 point_new_head
 
-###
-### Finished
-###
+# Finished
 logmsg "Incremental backup finished"
+
+# Ask to schedule backup
+prompt_user
